# Generated by Django 5.2.4 on 2025-08-04 10:28

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('case_info', models.TextField()),
                ('image_front', models.ImageField(upload_to=myapp.models.get_criminal_image_path_front)),
                ('image_left', models.ImageField(upload_to=myapp.models.get_criminal_image_path_left)),
                ('image_right', models.ImageField(upload_to=myapp.models.get_criminal_image_path_right)),
                ('image', models.ImageField(default='temp/default.jpg', upload_to='temp/')),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
